Repository out-fox-it/aj-ty-spojka, pull requests merged in 2021-03, with the labels that each got.

#77 Remove amplify
  .gitignore
  .vscode/settings.json
  amplify/.config/project-config.json
  amplify/README.md
  amplify/backend/auth/ajtyspojkac2740606/ajtyspojkac2740606-cloudformation-template.yml
  amplify/backend/auth/ajtyspojkac2740606/parameters.json
  amplify/backend/backend-config.json
  amplify/backend/tags.json
  amplify/cli.json
  package.json
  yarn.lock
Labels: dependencies

#78 Update yarn.lock according to actual package.json
  yarn.lock
Labels: dependencies

#80 💚 Fix and update GitHub Action for the Firebase hosting deployment
  .github/workflows/firebase-hosting-merge.yml
Labels: bug

#83 Firebase - login (fixed)
  src/components/App/index.tsx
  src/components/ButtonNav/index.tsx
  src/components/LoginForm/index.tsx
  src/components/NavBar/index.tsx
  src/components/Profile/index.tsx
  src/components/User/index.tsx
  src/pages/Authors.tsx
  src/pages/Contacts.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/Matching.tsx
  src/pages/Profile.tsx
  src/pages/Register.tsx
Labels: front-end

#119 Update dependencies
  .eslintrc.json
  .gitignore
  package.json
  src/components/Avatar/index.test.tsx
  src/components/Button/index.tsx
  tsconfig.json
  yarn.lock
Labels: dependencies, enhancement

#120 Create MatchingTabs component
  src/components/ButtonMatching/index.tsx
  src/components/ButtonMatching/styled.ts
  src/components/Matching/index.tsx
  src/components/Matching/styled.ts
  src/pages/Matching.tsx
Labels: enhancement, front-end
