Repository out-fox-it/aj-ty-spojka, pull requests merged in 2021-02, with the labels that each got.

#42 Fix ButtonNav
  src/components/ButtonNav/styled.ts
Labels: bug

#44 The Navigation Bar
  src/components/Button/styled.ts
  src/components/ButtonNav/index.tsx
  src/components/ButtonNav/styled.ts
  src/components/NavBar/index.tsx
  src/components/NavBar/styled.ts
  src/components/Navbar/index.tsx
  src/components/Navbar/styled.ts
  src/components/NavbarProfile/index.tsx
  src/pages/Home.tsx
  src/pages/Matching.tsx
  src/pages/Register.tsx
  yarn.lock
Labels: enhancement, front-end

#53 Add logo instead of styled-icon
  src/assets/Logo/index.tsx
  src/components/NavBar/index.tsx
  src/components/NavBar/styled.ts
Labels: enhancement, front-end

#48 Fixed NavBar for mobile
  src/components/App/styled.ts
  src/components/Button/styled.ts
  src/components/ButtonNav/styled.ts
Labels: bug, front-end

#57 Fixed menu
  src/components/App/styled.ts
  src/components/Button/styled.ts
  src/components/ButtonNav/styled.ts
  src/components/NavBar/styled.ts
Labels: bug, front-end

#67 Change Icon and libary
  package.json
  src/components/Avatar/styled.ts
  src/components/ButtonNav/index.tsx
  src/components/Profile/SocialNetwork/Network/index.tsx
Labels: front-end

#74 Refactor types to use type instead of interface
  src/components/Avatar/index.tsx
  src/components/Button/index.tsx
  src/components/ButtonNav/index.tsx
  src/components/NavBar/index.tsx
  src/components/Profile/Email/index.tsx
  src/components/Profile/Name/index.tsx
  src/components/Toggle/index.tsx
Labels: bug, front-end

#75 ⭕ Fix Message component styles
  src/components/Message/styled.ts
Labels: bug, front-end

#76 Fix Footer position
  src/components/Footer/index.tsx
  src/components/Footer/styled.ts
  src/components/Page/styled.ts
Labels: bug, front-end

#64 Add favicon
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/browserconfig.xml
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/manifest.json
Labels: enhancement
