Repository out-fox-it/aj-ty-spojka, pull requests merged in 2021-01, with the labels that each got.

#18 📝 Update Readme
  README.md
Labels: documentation

#23 Fix manifest.json file
  public/manifest.json
Labels: bug

#24 Update meta tags and theme colors in index files
  public/index.html
  src/index.css
Labels: enhancement

#28 Add Header component background image and style
  src/assets/header.svg
  src/components/Header/index.test.tsx
  src/components/Header/index.tsx
  src/components/Header/styled.ts
Labels: front-end

#30 Add buttons
  src/assets/buddy.svg
  src/assets/mentee.svg
  src/assets/mentor.svg
  src/components/Button/ButtonContent/index.test.tsx
  src/components/Button/ButtonContent/index.tsx
  src/components/Button/ButtonContent/styled.ts
  src/components/Button/ButtonFunction/index.test.tsx
  src/components/Button/ButtonFunction/index.tsx
  src/components/Button/ButtonFunction/styled.ts
  src/components/Button/ButtonLink/index.test.tsx
  src/components/Button/ButtonLink/index.tsx
  src/components/Button/ButtonLink/styled.ts
  src/components/Button/index.tsx
  src/components/ButtonNav/index.tsx
  src/components/ButtonNav/styled.ts
  src/pages/Home.tsx
Labels: front-end

#36 Bump immer from 7.0.9 to 8.0.1
  package.json
  yarn.lock
Labels: dependencies
